language: go
sudo: true

cache: ccache
addons: {apt: {packages: [yasm]}}

matrix:
  fast_finish: true
  include:
    # the actual compilin'
    - stage: Ubuntu14-go-master-tests
      os: linux
      env: JOB=tests-ubuntu14
      go: "master"
    - stage: Ubuntu14-go1.11-tests
      os: linux
      env: JOB=tests-ubuntu14
      go: "1.11.x"
    - stage: Ubuntu14-go1.10-tests
      os: linux
      env: JOB=tests-ubuntu14
      go: "1.10.x"
    - stage: Ubuntu14-go1.10-build
      os: linux
      env: JOB=build-ubuntu14
      go: "1.10.x"
    - stage: Ubuntu14-go1.9-build
      os: linux
      env: JOB=build-ubuntu14
      go: "1.9"
    # should be latest go
    # - stage: Ubuntu16-go1.10
    #   os: linux
    #   env:
    #     - JOB=build-ubuntu16
    #     - GOVER=1.10
    #   go: "1.10.x"
    #   services:
    #     - docker
    - stage: Ubuntu16-go1.9-build
      os: linux
      env:
        - JOB=build-ubuntu16
        - GOVER=1.9
      go: "1.9"
      services:
        - docker
    - stage: Win-Mingw-x64-build
      os: linux
      env:
        - JOB=build-mingw
        - WINARCH=x64
      services:
        - docker
    - stage: Win-Mingw-x32-build
      os: linux
      env:
        - JOB=build-mingw
        - WINARCH=x32
      services:
        - docker
    - stage: MacOS-Xcode10.1-build
      os: osx
      osx_image: xcode10.1
      env: JOB=build-osx
    - stage: MacOS-Xcode9.4-build
      os: osx
      osx_image: xcode9.4
      env: JOB=build-osx
    - stage: MacOS-Xcode9.3-build
      os: osx
      osx_image: xcode9.3
      env: JOB=build-osx
    - stage: MacOS-Xcode8.3-tests
      os: osx
      osx_image: xcode8.3
      env: JOB=tests-osx
    - stage: MacOS-Xcode8.3-build
      os: osx
      osx_image: xcode8.3
      env: JOB=build-osx
    # for ruby lower version and brew problem, not support
    # - stage: MacOS-Xcode7.3
    #   os: osx
    #   osx_image: xcode7.3
    #   env: JOB=build-osx

before_install:

before_script:

script:  "./.travis/$JOB.sh"

